USE [master]
GO
/****** Object:  Database [MyStudiesUOA]    Script Date: 1/21/2024 10:09:55 AM ******/
CREATE DATABASE [MyStudiesUOA]
GO
ALTER DATABASE [MyStudiesUOA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyStudiesUOA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyStudiesUOA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyStudiesUOA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyStudiesUOA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET RECOVERY FULL 
GO
ALTER DATABASE [MyStudiesUOA] SET  MULTI_USER 
GO
ALTER DATABASE [MyStudiesUOA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyStudiesUOA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyStudiesUOA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyStudiesUOA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyStudiesUOA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyStudiesUOA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MyStudiesUOA] SET QUERY_STORE = OFF
GO
USE [MyStudiesUOA]
GO
/****** Object:  Table [dbo].[GradeLeason]    Script Date: 1/21/2024 10:09:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GradeLeason](
	[Id] [int] NOT NULL,
	[TeachesLeasonId] [int] NOT NULL,
	[Grade] [int] NOT NULL,
 CONSTRAINT [PK_GradeLeason] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Leasons]    Script Date: 1/21/2024 10:09:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Leasons](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Semister] [int] NOT NULL,
	[DateCreated] [datetimeoffset](7) NOT NULL,
	[DateUpdated] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_Leasons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TeachesLeason]    Script Date: 1/21/2024 10:09:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TeachesLeason](
	[Id] [int] NOT NULL,
	[TeacherId] [int] NOT NULL,
	[LeasonId] [int] NOT NULL,
	[DateCreated] [datetimeoffset](7) NOT NULL,
	[DateUpdated] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_TeachesLeason] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 1/21/2024 10:09:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[FullName] [nvarchar](50) NOT NULL,
	[UserType] [int] NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](250) NOT NULL,
	[DateCreated] [datetimeoffset](7) NOT NULL,
	[DateUpdated] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GradeLeason]  WITH CHECK ADD  CONSTRAINT [FK_GradeLeason_TeachesLeason] FOREIGN KEY([TeachesLeasonId])
REFERENCES [dbo].[TeachesLeason] ([Id])
GO
ALTER TABLE [dbo].[GradeLeason] CHECK CONSTRAINT [FK_GradeLeason_TeachesLeason]
GO
ALTER TABLE [dbo].[TeachesLeason]  WITH CHECK ADD  CONSTRAINT [FK_TeachesLeason_Leasons] FOREIGN KEY([LeasonId])
REFERENCES [dbo].[Leasons] ([Id])
GO
ALTER TABLE [dbo].[TeachesLeason] CHECK CONSTRAINT [FK_TeachesLeason_Leasons]
GO
ALTER TABLE [dbo].[TeachesLeason]  WITH CHECK ADD  CONSTRAINT [FK_TeachesLeason_User] FOREIGN KEY([TeacherId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[TeachesLeason] CHECK CONSTRAINT [FK_TeachesLeason_User]
GO
USE [master]
GO
ALTER DATABASE [MyStudiesUOA] SET  READ_WRITE 
GO